"""Registry ports the SDK exposes.

Every registry is a Port (contract section 2: the core exposes platform-wide
truth through explicit interfaces). In-memory implementations live in
``atlas_core.infrastructure.registry``; a different backing store can swap in
behind these ports without plugins noticing.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from .capability import CapabilityId
from .contract import ContractDeclaration, ContractId, ContractImplementation
from .event import EventId
from .manifest import ClusterManifest, PluginManifest
from .plugin import PluginLifecycle


class ClusterRegistryPort(Protocol):
    def register(self, manifest: ClusterManifest) -> None:
        """Register a cluster. Raises if the cluster_id already exists."""
        ...
        ...

    def get(self, cluster_id: str) -> ClusterManifest: ...
    def all(self) -> list[ClusterManifest]: ...
    def exists(self, cluster_id: str) -> bool: ...


class PluginRegistryPort(Protocol):
    def register(self, manifest: PluginManifest) -> None:
        """Register a validated plugin. Raises if the plugin_id already exists."""
        ...
        ...

    def get(self, plugin_id: str) -> PluginManifest: ...
    def all(self) -> list[PluginManifest]: ...
    def list_by_cluster(self, cluster_id: str) -> list[PluginManifest]: ...
    def exists(self, plugin_id: str) -> bool: ...

    def lifecycle_state(self, plugin_id: str) -> PluginLifecycle: ...
    def mark(self, plugin_id: str, state: PluginLifecycle, reason: str | None = None) -> None:
        """Record a lifecycle transition for a registered plugin."""
        ...
        ...

    def failure_reason(self, plugin_id: str) -> str | None: ...


class CapabilityRegistryPort(Protocol):
    def register(self, capability: CapabilityId, plugin_id: str) -> None: ...
    def all(self) -> list[CapabilityId]: ...
    def exists(self, capability: CapabilityId) -> bool: ...
    def providers_of(self, capability: CapabilityId) -> list[str]:
        """Plugin ids that provide this capability."""
        ...
        ...

    def provided_by(self, plugin_id: str) -> list[CapabilityId]:
        """Capabilities provided by this plugin."""
        ...


class ContractRegistryPort(Protocol):
    def register(self, declaration: ContractDeclaration, plugin_id: str) -> None: ...
    def get(self, contract_id: ContractId) -> ContractImplementation: ...
    def all(self) -> list[ContractImplementation]: ...
    def exists(self, contract_id: ContractId) -> bool: ...

    def implementations_of(self, contract_id: ContractId) -> list[ContractImplementation]:
        """Every registered implementation of a contract (composability, section 13)."""
        ...

    def provided_by(self, plugin_id: str) -> list[ContractImplementation]: ...

    # --- runtime half (Gate I) --------------------------------------------

    def bind(self, contract_id: ContractId, plugin_id: str, instance: object) -> None:
        """Attach the live contract object of an ENABLED plugin."""
        ...

    def unbind(self, plugin_id: str) -> None:
        """Detach every contract of a plugin that is no longer enabled."""
        ...

    def invoke(self, contract_id: ContractId, request: object) -> object:
        """Call the single bound implementation of ``contract_id``."""
        ...

    def invoke_all(self, contract_id: ContractId, request: object) -> list[object]:
        """Call every bound implementation, in registration order."""
        ...


class EventRegistryPort(Protocol):
    def register_published(self, event: EventId, plugin_id: str) -> None: ...
    def register_subscribed(self, event: EventId, plugin_id: str) -> None: ...
    def all(self) -> list[EventId]: ...
    def exists(self, event: EventId) -> bool: ...
    def publishers_of(self, event: EventId) -> list[str]: ...
    def subscribers_of(self, event: EventId) -> list[str]: ...
    def published_by(self, plugin_id: str) -> Sequence[EventId]: ...
    def subscribed_by(self, plugin_id: str) -> Sequence[EventId]: ...


__all__ = [
    "CapabilityRegistryPort",
    "ClusterRegistryPort",
    "ContractRegistryPort",
    "EventRegistryPort",
    "PluginRegistryPort",
]
